services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  superset:
    build: .
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    volumes:
      - superset_data:/app/superset_home

volumes:
  postgres_data:
  superset_data:
