services:

    postgres:
        image: postgres:15
        environment:
            POSTGRES_DB: movies
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./migrations:/docker-entrypoint-initdb.d
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

    superset:
        build: .
        ports:
            - "8088:8088"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            SUPERSET_DATABASE_URI: postgresql+psycopg2://postgres:postgres@postgres:5432/movies
            SUPERSET_SECRET_KEY: superset
            SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config_minimal.py
            PYTHONPATH: /app/pythonpath:/app/pythonpath_docker
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: movies
        volumes:
            - superset_data:/app/superset_home

volumes:
    postgres_data:
    superset_data:
