// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Country struct {
	CountryID      int32       `json:"country_id"`
	CountryIsoCode pgtype.Text `json:"country_iso_code"`
	CountryName    pgtype.Text `json:"country_name"`
}

type Department struct {
	DepartmentID   int32       `json:"department_id"`
	DepartmentName pgtype.Text `json:"department_name"`
}

type Gender struct {
	GenderID int32       `json:"gender_id"`
	Gender   pgtype.Text `json:"gender"`
}

type Genre struct {
	GenreID   int32       `json:"genre_id"`
	GenreName pgtype.Text `json:"genre_name"`
}

type Keyword struct {
	KeywordID   int32       `json:"keyword_id"`
	KeywordName pgtype.Text `json:"keyword_name"`
}

type Language struct {
	LanguageID   int32       `json:"language_id"`
	LanguageCode pgtype.Text `json:"language_code"`
	LanguageName pgtype.Text `json:"language_name"`
}

type LanguageRole struct {
	RoleID       int32       `json:"role_id"`
	LanguageRole pgtype.Text `json:"language_role"`
}

type Movie struct {
	MovieID     int32          `json:"movie_id"`
	Title       pgtype.Text    `json:"title"`
	Budget      pgtype.Int4    `json:"budget"`
	Homepage    pgtype.Text    `json:"homepage"`
	Overview    pgtype.Text    `json:"overview"`
	Popularity  pgtype.Numeric `json:"popularity"`
	ReleaseDate pgtype.Date    `json:"release_date"`
	Revenue     pgtype.Int8    `json:"revenue"`
	Runtime     pgtype.Int4    `json:"runtime"`
	MovieStatus pgtype.Text    `json:"movie_status"`
	Tagline     pgtype.Text    `json:"tagline"`
	VoteAverage pgtype.Numeric `json:"vote_average"`
	VoteCount   pgtype.Int4    `json:"vote_count"`
}

type MovieCast struct {
	MovieID       pgtype.Int4 `json:"movie_id"`
	PersonID      pgtype.Int4 `json:"person_id"`
	CharacterName pgtype.Text `json:"character_name"`
	GenderID      pgtype.Int4 `json:"gender_id"`
	CastOrder     pgtype.Int4 `json:"cast_order"`
}

type MovieCompany struct {
	MovieID   pgtype.Int4 `json:"movie_id"`
	CompanyID pgtype.Int4 `json:"company_id"`
}

type MovieCrew struct {
	MovieID      pgtype.Int4 `json:"movie_id"`
	PersonID     pgtype.Int4 `json:"person_id"`
	DepartmentID pgtype.Int4 `json:"department_id"`
	Job          pgtype.Text `json:"job"`
}

type MovieGenre struct {
	MovieID pgtype.Int4 `json:"movie_id"`
	GenreID pgtype.Int4 `json:"genre_id"`
}

type MovieKeyword struct {
	MovieID   pgtype.Int4 `json:"movie_id"`
	KeywordID pgtype.Int4 `json:"keyword_id"`
}

type MovieLanguage struct {
	MovieID        pgtype.Int4 `json:"movie_id"`
	LanguageID     pgtype.Int4 `json:"language_id"`
	LanguageRoleID pgtype.Int4 `json:"language_role_id"`
}

type Person struct {
	PersonID   int32       `json:"person_id"`
	PersonName pgtype.Text `json:"person_name"`
}

type ProductionCompany struct {
	CompanyID   int32       `json:"company_id"`
	CompanyName pgtype.Text `json:"company_name"`
}

type ProductionCountry struct {
	MovieID   pgtype.Int4 `json:"movie_id"`
	CountryID pgtype.Int4 `json:"country_id"`
}
